org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

mod_id=omni_pipes
mod_name=Omni Pipes
mod_license=GPL-3.0-only
mod_version=1.0.0
mod_group_id=com.wizardg.omnipipes
