org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

mod_id=omni_pipes
mod_name=Omni Pipes
mod_license=GPL-3.0-only
mod_version=0.2b
mod_group_id=com.wizardg.omnipipes

# CurseForge file ids (curse maven)
rei_version=26.1.819
jei_file_id=8946405
observable_file_id=8880837
jade_file_id=8857417
better_advanced_tooltips_file_id=8568911
