org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

mod_id=aiop
mod_name=AIOP - All in One Pipe
mod_license=DSMSLv3
mod_version=0.1b
mod_group_id=com.wizardg.aiop

# CurseForge file ids (curse maven)
jei_file_id=8946405
observable_file_id=8880837
